apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: apitest-frontend
      context: apitest-frontend
    - image: apitest-testjobservice
      context: apitest-testjobservice
      jib:
        type: gradle 
    - image: apitest-testrunservice
      context: apitest-testrunservice
      jib:
        type: gradle    
    - image: apitest-testresultservice
      context: apitest-testresultservice
deploy:
  kubectl:
    manifests:
      - k8s/frontend.yaml
      - k8s/ingress.yaml
      - k8s/testjobservice.yaml
      - k8s/postgresql.yaml
      - k8s/redis.yaml
      - k8s/testresultservice.yaml
      - k8s/rabbitmq.yaml
      - k8s/testrunservice.yaml
