apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: eshop-frontend
      context: eshop-frontend
deploy:
  kubectl:
    manifests:
      - k8s/frontend.yaml
      - k8s/ingress.yaml
