apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: apitest-frontend
      context: apitest-frontend
    - image: apitest-testjobservice
      context: apitest-testjobservice
      jib:
        type: gradle 
deploy:
  kubectl:
    manifests:
      - k8s/frontend.yaml
      - k8s/ingress.yaml
      - k8s/testjobservice.yaml
      - k8s/postgresql.yaml
