apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: apitest-frontend
      context: apitest-frontend
deploy:
  kubectl:
    manifests:
      - k8s/frontend.yaml
      - k8s/ingress.yaml
