apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitest-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apitest-frontend
  template:
    metadata:
      labels:
        app: apitest-frontend
    spec:
      containers:
        - name: apitest-frontend
          image: apitest-frontend
          ports:
          - containerPort: 8080
          command: ["sh", "-c", "touch /tmp/healthy && sleep 86400"]
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apitest-frontend
spec:
  type: ClusterIP
  selector:
    app: apitest-frontend
  ports:
  - port: 8080
