apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apitest-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apitest-frontend
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: eshop-backend
            port:
              number: 8090
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: eshop-backend
            port:
              number: 8090
      - path: /api/testruns
        pathType: Prefix
        backend:
          service:
            name: apitest-testrunservice
            port:
              number: 8091
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: eshop-productservice
            port:
              number: 8092
      - path: /api/recommends
        pathType: Prefix
        backend:
          service:
            name: eshop-recommendservice
            port:
              number: 8093
      - path: /api/testresults
        pathType: Prefix
        backend:
          service:
            name: apitest-testresultservice
            port:
              number: 8094
      - path: /api/testjobs
        pathType: Prefix
        backend:
          service:
            name: apitest-testjobservice
            port:
              number: 8095
