apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitest-testresultservice
spec:
  replicas: 2      
  selector:
    matchLabels:
      app: apitest-testresultservice
  template:
    metadata:
      labels:
        app: apitest-testresultservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: apitest-testresultservice
        image: apitest-testresultservice
        ports:
        - containerPort: 8094
        env:
        - name: PORT
          value: "8094"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apitest-testresultservice
spec:
  type: ClusterIP
  selector:
    app: apitest-testresultservice
  ports:
  - name: api
    port: 8094
    targetPort: 8094
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: apitest-testresultservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apitest-testresultservice
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
