apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitest-testjobservice
spec:
  replicas: 2       
  selector:
    matchLabels:
      app: apitest-testjobservice
  template:
    metadata:
      labels:
        app: apitest-testjobservice
    spec:
      containers:
        - name: apitest-testjobservice
          image: apitest-testjobservice
          ports:
          - containerPort: 8095
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/eshop_db"
            # - name: SPRING_PROFILES_ACTIVE
            #   value: "chaos-monkey"  
---
apiVersion: v1
kind: Service
metadata:
  name: apitest-testjobservice
spec:
  type: ClusterIP
  selector:
    app: apitest-testjobservice
  ports:
  - port: 8095
