pipeline {
  environment {
    PROJECT_ID = 'architect-certification-289902'
    CLASS_ID = '2301'
    MEMBER_ID = '41'
  }
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: remote-agent
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/kaniko/config.json"
"""      
    }
  }
  stages {
    stage('Build & Push') {
      steps {
        container(name: 'kaniko', shell: '/busybox/sh') {
          dir('eshop-recommendservice') {
            withCredentials([file(credentialsId: 'gcr-credential', variable: 'GCR_CREDENTIAL_JSON')]) {
              sh "cp $GCR_CREDENTIAL_JSON /kaniko/config.json"
              sh "\
                  /kaniko/executor \
                  --context=dir://./ \
                  --destination=gcr.io/$PROJECT_ID/$CLASS_ID/$MEMBER_ID/eshop-recommendservice:$BUILD_ID \
              "
            }
          }
        }
      }
    }
  }
}
